// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePhoto(arg1) {
  return window['go']['main']['App']['ApprovePhoto'](arg1);
}

export function CheckDatabaseHealth() {
  return window['go']['main']['App']['CheckDatabaseHealth']();
}

export function CheckExifToolStatus() {
  return window['go']['main']['App']['CheckExifToolStatus']();
}

export function CleanOldLogs(arg1) {
  return window['go']['main']['App']['CleanOldLogs'](arg1);
}

export function ClearAllPhotoSelection(arg1) {
  return window['go']['main']['App']['ClearAllPhotoSelection'](arg1);
}

export function DeleteBatch(arg1) {
  return window['go']['main']['App']['DeleteBatch'](arg1);
}

export function DeleteStockConfig(arg1) {
  return window['go']['main']['App']['DeleteStockConfig'](arg1);
}

export function ForceUpdateDefaultPrompts() {
  return window['go']['main']['App']['ForceUpdateDefaultPrompts']();
}

export function GetAIModels(arg1) {
  return window['go']['main']['App']['GetAIModels'](arg1);
}

export function GetAvailableUploaders() {
  return window['go']['main']['App']['GetAvailableUploaders']();
}

export function GetBatchDetails(arg1) {
  return window['go']['main']['App']['GetBatchDetails'](arg1);
}

export function GetBatchEvents(arg1, arg2) {
  return window['go']['main']['App']['GetBatchEvents'](arg1, arg2);
}

export function GetBatchPhotos(arg1) {
  return window['go']['main']['App']['GetBatchPhotos'](arg1);
}

export function GetDefaultLanguage() {
  return window['go']['main']['App']['GetDefaultLanguage']();
}

export function GetFolderContents(arg1) {
  return window['go']['main']['App']['GetFolderContents'](arg1);
}

export function GetPhoto(arg1) {
  return window['go']['main']['App']['GetPhoto'](arg1);
}

export function GetPhotoEvents(arg1) {
  return window['go']['main']['App']['GetPhotoEvents'](arg1);
}

export function GetPhotoSelectionStatus(arg1) {
  return window['go']['main']['App']['GetPhotoSelectionStatus'](arg1);
}

export function GetPhotoThumbnail(arg1) {
  return window['go']['main']['App']['GetPhotoThumbnail'](arg1);
}

export function GetProcessedBatches() {
  return window['go']['main']['App']['GetProcessedBatches']();
}

export function GetProcessingHistory(arg1) {
  return window['go']['main']['App']['GetProcessingHistory'](arg1);
}

export function GetProcessingProgress(arg1) {
  return window['go']['main']['App']['GetProcessingProgress'](arg1);
}

export function GetQueueStatus() {
  return window['go']['main']['App']['GetQueueStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStockConfigs() {
  return window['go']['main']['App']['GetStockConfigs']();
}

export function GetStockTemplates() {
  return window['go']['main']['App']['GetStockTemplates']();
}

export function GetUploadProgress(arg1) {
  return window['go']['main']['App']['GetUploadProgress'](arg1);
}

export function GetUploadQueueStatus() {
  return window['go']['main']['App']['GetUploadQueueStatus']();
}

export function ProcessPhotoFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessPhotoFolder'](arg1, arg2, arg3);
}

export function RegeneratePhotoMetadata(arg1, arg2) {
  return window['go']['main']['App']['RegeneratePhotoMetadata'](arg1, arg2);
}

export function RejectPhoto(arg1) {
  return window['go']['main']['App']['RejectPhoto'](arg1);
}

export function ResetPhotoToProcessed(arg1) {
  return window['go']['main']['App']['ResetPhotoToProcessed'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveStockConfig(arg1) {
  return window['go']['main']['App']['SaveStockConfig'](arg1);
}

export function SelectAllPhotosForUpload(arg1) {
  return window['go']['main']['App']['SelectAllPhotosForUpload'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetPhotoSelectedForUpload(arg1, arg2) {
  return window['go']['main']['App']['SetPhotoSelectedForUpload'](arg1, arg2);
}

export function SetPhotoStatus(arg1, arg2) {
  return window['go']['main']['App']['SetPhotoStatus'](arg1, arg2);
}

export function StartQueueProcessing() {
  return window['go']['main']['App']['StartQueueProcessing']();
}

export function StopQueueProcessing() {
  return window['go']['main']['App']['StopQueueProcessing']();
}

export function StopUploadQueue() {
  return window['go']['main']['App']['StopUploadQueue']();
}

export function TestStockConnection(arg1) {
  return window['go']['main']['App']['TestStockConnection'](arg1);
}

export function ToggleStockActive(arg1) {
  return window['go']['main']['App']['ToggleStockActive'](arg1);
}

export function UpdateAIPrompt(arg1, arg2) {
  return window['go']['main']['App']['UpdateAIPrompt'](arg1, arg2);
}

export function UpdatePhotoMetadata(arg1, arg2) {
  return window['go']['main']['App']['UpdatePhotoMetadata'](arg1, arg2);
}

export function UploadApprovedPhotos(arg1) {
  return window['go']['main']['App']['UploadApprovedPhotos'](arg1);
}

export function UploadSelectedPhotos(arg1, arg2) {
  return window['go']['main']['App']['UploadSelectedPhotos'](arg1, arg2);
}

export function ValidateStockConfig(arg1) {
  return window['go']['main']['App']['ValidateStockConfig'](arg1);
}
